version: "3.1"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: tutorial
            POSTGRES_DB: iam
            POSTGRES_PASSWORD: privatepassword
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data

    server:
        build: .
        volumes:
            -   ./:/app
        ports:
            -   8080:3000
        env_file:
            -   .env
        links:
            -   postgres
        command: ['npm', 'start']